In [1]:
# Artificial Neural Networks

In [2]:
# Importing the libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Importing the dataset
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
# Importing the Keras libraries and packages
import keras

Using TensorFlow backend.


In [10]:
from keras.models import Sequential
from keras.layers import Dense

In [11]:
# Initializing the ANN
classifier = Sequential()

In [13]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', 
                     activation = 'relu', input_dim = 11))

F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', 
                     activation = 'relu'))

F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [15]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', 
                     activation = 'sigmoid'))

F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [17]:
y_pred

array([[0.49995375],
       [0.50002605],
       [0.49996984],
       ...,
       [0.49993348],
       [0.50000036],
       [0.50003403]], dtype=float32)

In [18]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
# Fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

F:\Installed\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 292us/step - loss: 0.4861 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4284 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4217 - acc: 0.7987
Epoch 4/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4181 - acc: 0.8221
Epoch 5/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4155 - acc: 0.8300
Epoch 6/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4140 - acc: 0.8317
Epoch 7/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4124 - acc: 0.8335
Epoch 8/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4113 - acc: 0.8324
Epoch 9/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4105 - acc: 0.8322
Epoch 10/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.4092 - acc: 0.8345

8000/8000 [==============================] - 1s 166us/step - loss: 0.4005 - acc: 0.8364
Epoch 83/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3999 - acc: 0.8354
Epoch 84/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.4002 - acc: 0.8335
Epoch 85/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4001 - acc: 0.8369
Epoch 86/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3997 - acc: 0.8355
Epoch 87/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3999 - acc: 0.8364
Epoch 88/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3998 - acc: 0.8350
Epoch 89/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3999 - acc: 0.8351
Epoch 90/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3997 - acc: 0.8367
Epoch 91/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3991 - acc: 0.8347
Epo

In [20]:
# Predicting the test set result
y_pred = classifier.predict(X_test)

In [22]:
y_pred

array([[0.18820348],
       [0.33680636],
       [0.18828283],
       ...,
       [0.17118345],
       [0.17428927],
       [0.09666966]], dtype=float32)

In [23]:
y_pred = (y_pred>0.5)

In [24]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [25]:
print(cm)

[[1539   56]
 [ 267  138]]
